/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Karton;
import domen.Korisnik;
import domen.Pregled;
import domen.Uput;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modeli.ModelTabelePregledi;
import paneli.PnlAzuriranjePregleda;
import paneli.PnlKartonPretraga;
import paneli.PnlKartonUnosIzmena;
import paneli.PnlLekUnos;
import paneli.PnlPregledPretraga;
import paneli.PnlPregledUnos;
import paneli.PnlPretragaLekova;
import sesija.Sesija;

/**
 *
 * @author minoc
 */
public class GlavnaForma extends javax.swing.JFrame {

    FrmForma forma;
    FrmDialog dialog;
    
    ModelTabelePregledi modelTab;
    Date datumPregleda;
    
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        this.setTitle("Ordinacija Dermatolog");
        lblLekar.setText(sesija.Sesija.getInstanca().getKorisnik().toString());
      
        kontroler.Kontroler.getInstanca().setForma(this);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLekar = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKarton = new javax.swing.JMenu();
        miUnosKartona = new javax.swing.JMenuItem();
        miPretragaKartona = new javax.swing.JMenuItem();
        menuPregled = new javax.swing.JMenu();
        miNoviPregled = new javax.swing.JMenuItem();
        miPretragaAzuriranjaPregleda = new javax.swing.JMenuItem();
        menuLek = new javax.swing.JMenu();
        menuNoviLek = new javax.swing.JMenuItem();
        miPretragaLekova = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblLekar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnOdjava.setText("Odjava");
        btnOdjava.setHideActionText(true);
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        menuKarton.setText("Karton");

        miUnosKartona.setText("Novi karton");
        miUnosKartona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosKartonaActionPerformed(evt);
            }
        });
        menuKarton.add(miUnosKartona);

        miPretragaKartona.setText("Pretraga/Izmena kartona");
        miPretragaKartona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaKartonaActionPerformed(evt);
            }
        });
        menuKarton.add(miPretragaKartona);

        jMenuBar1.add(menuKarton);

        menuPregled.setText("Pregled");

        miNoviPregled.setText("Novi pregled");
        miNoviPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviPregledActionPerformed(evt);
            }
        });
        menuPregled.add(miNoviPregled);

        miPretragaAzuriranjaPregleda.setText("Pretraga/Azuriranje pregleda");
        miPretragaAzuriranjaPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAzuriranjaPregledaActionPerformed(evt);
            }
        });
        menuPregled.add(miPretragaAzuriranjaPregleda);

        jMenuBar1.add(menuPregled);

        menuLek.setText("Lek");

        menuNoviLek.setText("Novi lek");
        menuNoviLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviLekActionPerformed(evt);
            }
        });
        menuLek.add(menuNoviLek);

        miPretragaLekova.setText("Pretraga lekova");
        miPretragaLekova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaLekovaActionPerformed(evt);
            }
        });
        menuLek.add(miPretragaLekova);

        jMenuBar1.add(menuLek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 579, Short.MAX_VALUE)
                .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOdjava)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPretragaKartonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaKartonaActionPerformed
        PnlKartonPretraga pnl = new PnlKartonPretraga();
        forma = new FrmForma((IPanel) pnl);
        forma.setParent(this);
        forma.setVisible(true);
    }//GEN-LAST:event_miPretragaKartonaActionPerformed

    private void miPretragaAzuriranjaPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAzuriranjaPregledaActionPerformed
        PnlPregledPretraga pnl = new PnlPregledPretraga();
        forma = new FrmForma((IPanel) pnl);
        forma.setParent(this);
        forma.setVisible(true);
    }//GEN-LAST:event_miPretragaAzuriranjaPregledaActionPerformed

    private void miNoviPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviPregledActionPerformed
        PnlPregledUnos pnl = new PnlPregledUnos();
        forma = new FrmForma((IPanel) pnl);
        forma.setParent(this);
        forma.setVisible(true);
        
    }//GEN-LAST:event_miNoviPregledActionPerformed

    private void miUnosKartonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosKartonaActionPerformed
        PnlKartonUnosIzmena pnl= new PnlKartonUnosIzmena(FrmMod.unos);
        dialog = new FrmDialog(this, true, (IPanel) pnl);
        dialog.setVisible(true);  
    }//GEN-LAST:event_miUnosKartonaActionPerformed

    private void menuNoviLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviLekActionPerformed
        PnlLekUnos pnl = new PnlLekUnos(FrmMod.unos);
        dialog = new FrmDialog(this, true, (IPanel) pnl);
        dialog.setVisible(true);       
    }//GEN-LAST:event_menuNoviLekActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        try {
//            String odgovor = kontroler.Kontroler.getInstanca().odjavaSaSistema(Sesija.getInstanca().getKorisnik());
//            JOptionPane.showMessageDialog(this, odgovor);
//            FrmPrijava form = new FrmPrijava();
//            form.setVisible(true);
//            dispose();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
          try {
            String odgovor = kontroler.Kontroler.getInstanca().odjavaSaSistema(Sesija.getInstanca().getKorisnik());
            JOptionPane.showMessageDialog(this, odgovor);
            FrmPrijava form = new FrmPrijava();
            form.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void miPretragaLekovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaLekovaActionPerformed
         PnlPretragaLekova pnl = new PnlPretragaLekova();
        forma = new FrmForma((IPanel) pnl);
        forma.setParent(this);
        forma.setVisible(true);
    }//GEN-LAST:event_miPretragaLekovaActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JMenu menuKarton;
    private javax.swing.JMenu menuLek;
    private javax.swing.JMenuItem menuNoviLek;
    private javax.swing.JMenu menuPregled;
    private javax.swing.JMenuItem miNoviPregled;
    private javax.swing.JMenuItem miPretragaAzuriranjaPregleda;
    private javax.swing.JMenuItem miPretragaKartona;
    private javax.swing.JMenuItem miPretragaLekova;
    private javax.swing.JMenuItem miUnosKartona;
    // End of variables declaration//GEN-END:variables


   
}
