/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneli;

import domen.OpstaDomenskaKlasa;
import domen.TipAnalize;
import domen.Uput;
import forme.FrmDialog;
import forme.FrmForma;
import forme.FrmMod;
import forme.GlavnaForma;
import forme.IPanel;
import java.awt.Frame;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;
import modeli.ModelTabeleUputi;

/**
 *
 * @author minna
 */
public class PnlIzdavanjeUputa extends javax.swing.JPanel implements IPanel{

    FrmMod mod;
    ModelTabeleUputi model;
    Uput u;
    
    /**
     * Creates new form PnlIzdavanjeUputa
     */
    public PnlIzdavanjeUputa(FrmMod frmMod) {
        initComponents();
         popuniCmb();
        mod=frmMod;
        spremiFormu(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbTipAnalize = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnSacuvaj = new javax.swing.JButton();

        jLabel1.setText("Tip analize:");

        cmbTipAnalize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipAnalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipAnalizeActionPerformed(evt);
            }
        });

        jLabel2.setText("Opis:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipAnalize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipAnalize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

       
            if (txtOpis.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
                return;
            }

            TipAnalize analiza=(TipAnalize) cmbTipAnalize.getSelectedItem();
            String opis=txtOpis.getText();

            Uput u= new Uput(0, opis, analiza);
            
        try {
            //String poruka = Kontroler.getInstanca().unesiUput(u);
           // JOptionPane.showMessageDialog(this, poruka);
          

            //  sesija.Sesija.getInstanca().getUputi().add(u);
            sesija.Sesija.getInstanca().getMapa().put("trenutniUput", u);
            System.out.println(u);
//             if (((SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
//                    return;
//                }
            ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
           (((FrmForma) SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke(); 
         } catch (NullPointerException ex) {   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno cuvanje");
            Logger.getLogger(PnlIzdavanjeUputa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void cmbTipAnalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipAnalizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipAnalizeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbTipAnalize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void popuniCmb() {
         try {
            cmbTipAnalize.removeAllItems();
            List<TipAnalize> lista=Kontroler.getInstanca().vratiTipoveAnaliza();
            System.out.println(lista);
            for (TipAnalize ta : lista) {
                cmbTipAnalize.addItem(ta);
            }
        } catch (IOException ex) {
            Logger.getLogger(PnlIzdavanjeUputa.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(PnlIzdavanjeUputa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PnlIzdavanjeUputa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void spremiFormu(FrmMod m) {
       
        switch (m) {
            case unos:
                btnSacuvaj.setVisible(true);

                break;
            case izmena:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniUput"));
                btnSacuvaj.setVisible(false);

                break;
            case pregled:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniUput"));
                btnSacuvaj.setVisible(false);
                txtOpis.setEditable(false);
                cmbTipAnalize.setEnabled(false);
                break;
        }
    
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Uput u = (Uput) odk;
        if (u != null) {
            txtOpis.setText(u.getOpis());
            cmbTipAnalize.setSelectedItem(u.getTipAnalize());

        }
    }

    public FrmMod getMod() {
        return mod;
    }

    public void setMod(FrmMod mod) {
        this.mod = mod;
    }
     
    
}
