/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneli;

import domen.Lek;
import domen.OpstaDomenskaKlasa;
import domen.Recept;
import forme.FrmDialog;
import forme.FrmForma;
import forme.FrmMod;
import forme.GlavnaForma;
import forme.IPanel;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import kontroler.Kontroler;
import modeli.ModelTabeleRecepti;

/**
 *
 * @author minna
 */
public class PnlIzdavanjeRecepta extends javax.swing.JPanel implements IPanel{

    
    FrmMod mod;
    Lek l;
    
    ModelTabeleRecepti model;
    /**
     * Creates new form PnlIzdavanjeRecepta
     */
    public PnlIzdavanjeRecepta(FrmMod frmMod) {
        initComponents();
        mod=frmMod;
        lblPotpisLekara.setText(sesija.Sesija.getInstanca().getKorisnik().toString());
        srediFormu(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPotpisLekara = new javax.swing.JLabel();
        btnPretragaLekova = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLekInfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUputstvo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Recept"));

        lblPotpisLekara.setText("lekar");

        btnPretragaLekova.setText("Pretraga lekova");
        btnPretragaLekova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaLekovaActionPerformed(evt);
            }
        });

        jLabel1.setText("Lek:");

        jLabel3.setText("Uputstvo:");

        txtUputstvo.setColumns(20);
        txtUputstvo.setRows(5);
        jScrollPane1.setViewportView(txtUputstvo);

        jLabel4.setText("Ordinacija Dermatolog");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblPotpisLekara, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblLekInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(btnPretragaLekova, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(btnPretragaLekova)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblLekInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lblPotpisLekara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaLekovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaLekovaActionPerformed
        PnlPretragaLekova panel = new PnlPretragaLekova();
        panel.izaberi();
        //FrmDialog forma = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnPretragaLekovaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
         if (l == null || txtUputstvo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate odabrati lek i uneti uputstvo!");
            return;
        }
        
        String uputstvo = txtUputstvo.getText();
        String potpis=lblPotpisLekara.getText();
        
        Recept r= new Recept(0, uputstvo, potpis, l);
        
//        model.ubaciUTabelu(r);
        
            try {
                //String poruka = Kontroler.getInstanca().unesiRecept(r);
               // JOptionPane.showMessageDialog(this, poruka);
               sesija.Sesija.getInstanca().getMapa().put("trenutniRecept", r);
               //sesija.Sesija.getInstanca().getRecepti().add(r);
              //  System.out.println(sesija.Sesija.getInstanca().getRecepti());
              // System.out.println(r);
//                    if (((SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
//                        return;
//                    }
               ((FrmForma) SwingUtilities.getWindowAncestor(this)).dispose();
               (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke(); 
            } catch (NullPointerException ex) {
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje");
                Logger.getLogger(PnlIzdavanjeRecepta.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    @Override
    public void popuniPodatke() {
       l= (Lek) sesija.Sesija.getInstanca().getMapa().get("trenutniLek");
       lblLekInfo.setText(l+" "+l.getKoncentracija());
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretragaLekova;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLekInfo;
    private javax.swing.JLabel lblPotpisLekara;
    private javax.swing.JTextArea txtUputstvo;
    // End of variables declaration//GEN-END:variables

    private void srediFormu(FrmMod mod) {
        switch (mod) {
            case unos:
                  this.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Izdavanje recepta",TitledBorder.LEFT, TitledBorder.TOP));
                btnSacuvaj.setVisible(true);
                break;
                
            case pregled:
                this.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Recept",TitledBorder.LEFT, TitledBorder.TOP));
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniRecept"));
                btnSacuvaj.setVisible(false);
                btnPretragaLekova.setVisible(false);
                txtUputstvo.setEditable(false);
                break;
        }
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Recept r=(Recept) odk;
        
        lblLekInfo.setText(r.getLek()+" "+r.getLek().getKoncentracija());
        txtUputstvo.setText(r.getUputstvo());
        lblPotpisLekara.setText(r.getPotpisLekara());
    }
    
    

}
