/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneli;

import domen.Lek;
import domen.OpstaDomenskaKlasa;
import forme.FrmDialog;
import forme.FrmForma;
import forme.FrmMod;
import forme.GlavnaForma;
import forme.IPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import kontroler.Kontroler;

/**
 *
 * @author minna
 */
public class PnlLekUnos extends javax.swing.JPanel implements IPanel{

    
    private FrmMod model;
    /**
     * Creates new form PnlLekUnos
     */
    public PnlLekUnos(FrmMod mod) {
        initComponents();
        model=mod;
        spremiFormu(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        txtKoncentracija = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKontraind = new javax.swing.JTextArea();
        txtGrupa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNamena = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSastav = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lek"));
        setAutoscrolls(true);

        jLabel4.setText("Namena:");

        jLabel5.setText("Sastav:");

        jLabel6.setText("Kontraindikacije:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        txtKontraind.setColumns(20);
        txtKontraind.setRows(5);
        jScrollPane1.setViewportView(txtKontraind);

        txtNamena.setColumns(20);
        txtNamena.setRows(5);
        jScrollPane2.setViewportView(txtNamena);

        txtSastav.setColumns(20);
        txtSastav.setRows(5);
        jScrollPane3.setViewportView(txtSastav);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Koncentracija:");

        jLabel3.setText("Grupa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(txtKoncentracija)
                            .addComponent(txtGrupa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKoncentracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(btnSacuvaj)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        String naziv=txtNaziv.getText();
        String konc=txtKoncentracija.getText();
        String grupa=txtGrupa.getText();
        String namena=txtNamena.getText();
        String sastav=txtSastav.getText();
        String kontraind=txtKontraind.getText();

        boolean val=validacija(naziv,konc,grupa,sastav,kontraind);

        if(val){
            Lek l= new Lek(0, naziv, konc, grupa, namena, sastav, kontraind);
            try {
                String poruka=Kontroler.getInstanca().unesiLek(l);
                JOptionPane.showMessageDialog(this, poruka);
                sesija.Sesija.getInstanca().getMapa().put("trenutniLek", l);
                System.out.println(l);
                if (((SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
                    return;
                }
                ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
                (((FrmForma) SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
            } catch (NullPointerException e) {
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno cuvanje!");
                Logger.getLogger(PnlLekUnos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    public FrmMod getModel() {
        return model;
    }

    public void setModel(FrmMod model) {
        this.model = model;
    }

    private void spremiFormu(FrmMod frmMod) {
       switch (frmMod) {
            case unos:
                  this.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Unos novog leka u bazu lekova",TitledBorder.LEFT, TitledBorder.TOP));
                btnSacuvaj.setVisible(true);
                //btnIzmeni.setVisible(false);
                break;
                
            case izmena:
                this.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Izmena leka",TitledBorder.LEFT, TitledBorder.TOP));
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniLek"));
                btnSacuvaj.setVisible(false);
                //btnIzmeni.setVisible(true);
                break;
                
            case pregled:
                this.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Prikaz leka",TitledBorder.LEFT, TitledBorder.TOP));
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniLek"));
                btnSacuvaj.setVisible(false);
                txtNaziv.setEditable(false);
                txtKoncentracija.setEditable(false);
                txtGrupa.setEditable(false);
                txtNamena.setEditable(false);
                txtSastav.setEditable(false);
                txtKontraind.setEditable(false);
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtGrupa;
    private javax.swing.JTextField txtKoncentracija;
    private javax.swing.JTextArea txtKontraind;
    private javax.swing.JTextArea txtNamena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtSastav;
    // End of variables declaration//GEN-END:variables

    private boolean validacija(String naziv, String konc, String grupa, String sastav, String kontraind) {
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv leka!");
            return false;
        }
        if (grupa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti grupu kojoj lek pripada!");
            return false;
        }
        if (sastav.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti sastav leka!");
            return false;

        }
        if (kontraind.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti kontraindikacije leka!");
            return false;

        }
       
        return true;
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
         Lek l = (Lek) odk;
        if (l != null) {
            txtNaziv.setText(l.getNaziv());
            txtKoncentracija.setText(l.getKoncentracija());
            txtGrupa.setText(l.getGrupaLekova());
            txtNamena.setText(l.getNamena());
            txtSastav.setText(l.getSastav());
            txtKontraind.setText(l.getKontraindikacije());


        }
    }

    
}
