/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleKorisnici;
import server.PokretanjeServera;

/**
 *
 * @author minoc
 */
public class FrmServer extends javax.swing.JFrame {

    PokretanjeServera ps;
    
    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
        srediTabelu();
        pnlKorisnici.setVisible(false);
        this.setTitle("Server");
        postaviStatus("Server nije pokrenut", true);
        Kontroler.getInstanca().setForma(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        pnlKonfiguracija = new javax.swing.JPanel();
        btnKonfBaze = new javax.swing.JButton();
        btnKonfKonekcije = new javax.swing.JButton();
        pnlKorisnici = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKorisnici = new javax.swing.JTable();
        btnOdjavi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        pnlKonfiguracija.setBorder(javax.swing.BorderFactory.createTitledBorder("Konfiguracija"));

        btnKonfBaze.setText("Konfiguracija baze");
        btnKonfBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfBazeActionPerformed(evt);
            }
        });

        btnKonfKonekcije.setText("Konfiguracija konekcije");
        btnKonfKonekcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfKonekcijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKonfiguracijaLayout = new javax.swing.GroupLayout(pnlKonfiguracija);
        pnlKonfiguracija.setLayout(pnlKonfiguracijaLayout);
        pnlKonfiguracijaLayout.setHorizontalGroup(
            pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonfiguracijaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnKonfBaze, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnKonfKonekcije, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKonfiguracijaLayout.setVerticalGroup(
            pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonfiguracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKonfBaze)
                    .addComponent(btnKonfKonekcije))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKorisnici.setBorder(javax.swing.BorderFactory.createTitledBorder("Korisnici"));

        tblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKorisnici);

        btnOdjavi.setText("Odjavi");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKorisniciLayout = new javax.swing.GroupLayout(pnlKorisnici);
        pnlKorisnici.setLayout(pnlKorisniciLayout);
        pnlKorisniciLayout.setHorizontalGroup(
            pnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKorisniciLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdjavi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlKorisniciLayout.setVerticalGroup(
            pnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKorisniciLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOdjavi)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlKorisnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKonfiguracija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokreni)
                        .addGap(18, 18, 18)
                        .addComponent(btnZaustavi)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblStatus)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addGap(18, 18, 18)
                .addComponent(pnlKonfiguracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        ps = new PokretanjeServera();
        ps.start();
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        ps.zaustavi();
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
         ModelTabeleKorisnici model = (ModelTabeleKorisnici) tblKorisnici.getModel();
        int index = tblKorisnici.getSelectedRow();
        if (index != -1) {
            Korisnik k = model.izbaciRed(index);
             try {
                 Kontroler.getInstanca().izbaciKorisnika(k);
             } catch (IOException ex) {
                 Logger.getLogger(FrmServer.class.getName()).log(Level.SEVERE, null, ex);
             }
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati red tabele!");
        }
    }//GEN-LAST:event_btnOdjaviActionPerformed

    private void btnKonfBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfBazeActionPerformed
        FrmKonfiguracijaBaze frm = new FrmKonfiguracijaBaze(this, true);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnKonfBazeActionPerformed

    private void btnKonfKonekcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfKonekcijeActionPerformed
         FrmKonfiguracijaKonekcije frm = new FrmKonfiguracijaKonekcije(this, true);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnKonfKonekcijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfBaze;
    private javax.swing.JButton btnKonfKonekcije;
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlKonfiguracija;
    private javax.swing.JPanel pnlKorisnici;
    private javax.swing.JTable tblKorisnici;
    // End of variables declaration//GEN-END:variables

//    private void serverPokrenut() {
//        btnPokreniZaustavi.setText("Zaustavi Server");
//        lblStatus.setText("Server pokrenut");
//    }
//
//    private void serverNijePokrenut() {
//        btnPokreniZaustavi.setText("Pokreni server");
//        lblStatus.setText("Server nije pokrenut");
//    }
//
//    private void srediFormu() {
//        this.setTitle("Server");
//        btnPokreniZaustavi.setText("PokreniServer");
//        lblStatus.setText("Server nije pokrenut");
//    }

    public void postaviStatus(String poruka, boolean signal) {
       lblStatus.setText(poruka);
        btnPokreni.setEnabled(signal);
        btnZaustavi.setEnabled(!signal);
        pnlKorisnici.setVisible(!signal);
       pnlKonfiguracija.setVisible(signal);
    }

    public void odjaviKorisnika(Korisnik kor) {
        ModelTabeleKorisnici model = (ModelTabeleKorisnici) tblKorisnici.getModel();
        model.izbaciKorisnika(kor);
    }

    public void dodajPrijavljenogKorisnika(Korisnik k) {
         ModelTabeleKorisnici model = (ModelTabeleKorisnici) tblKorisnici.getModel();
        model.dodajKorisnika(k);
    }

    public void srediTabelu() {
        ModelTabeleKorisnici model = new ModelTabeleKorisnici();
        tblKorisnici.setModel(model);
    }

}
